#!/bin/bash
# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
COL_MAGENTA=$ESC_SEQ"35;01m"
COL_CYAN=$ESC_SEQ"36;01m"
COL_GRAY=$ESC_SEQ"30;01m"
COL_WHITE=$ESC_SEQ"37;01m"
echo
echo -e '#############################################'
echo -e '| JEREMYMEILE.CH                            |'
echo -e '|                                           |'
echo -e '| ACE lib builder   '$COL_BLUE'[ACEtool]'$COL_RESET'     |'
echo -e '#############################################'
echo
echo -ne $COL_BLUE'[ACEtool] '$COL_RESET'Checking source ...'
if
	test -f ~/Downloads/ACE-6.2.1.tar.gz > /dev/null 2>/tmp/TDBtool_errorMSG
then
	if [ `echo $(md5 -q ~/Downloads/ACE-6.2.1.tar.gz)` != "119a8b1310c6dd817a674a0c2f9679e8" ]
	then
		echo -e $COL_RED' Not found'$COL_RESET
		echo -ne $COL_BLUE'[ACEtool] '$COL_RESET'Getting source ...'
		cd ~/Downloads
		rm -d -f -r ACE-6.2.1.tar.gz > /dev/null 2>/tmp/TDBtool_errorMSG
		if
			curl -O -s http://download.dre.vanderbilt.edu/previous_versions/ACE-6.2.1.tar.gz > /dev/null 2>/tmp/TDBtool_errorMSG
		then
			echo -e $COL_GREEN' OK'$COL_RESET
		else
			echo -e $COL_RED' error'$COL_RESET
			echo -e $COL_RED'    error '$COL_WHITE$(/bin/cat /tmp/TDBtool_errorMSG)$COL_RESET
			exit 1
		fi
	else
		echo -e $COL_GREEN' OK'$COL_RESET
	fi
else
	echo -e $COL_RED' Not found'$COL_RESET
	echo -ne $COL_BLUE'[ACEtool] '$COL_RESET'Getting source ...'
	cd ~/Downloads
	rm -d -f -r ACE-6.2.1.tar.gz
		if
			curl -O -s http://download.dre.vanderbilt.edu/previous_versions/ACE-6.2.1.tar.gz > /dev/null 2>/tmp/TDBtool_errorMSG
		then
			echo -e $COL_GREEN' OK'$COL_RESET
		else
			echo -e $COL_RED' error'$COL_RESET
			echo -e $COL_RED'    error '$COL_WHITE$(/bin/cat /tmp/TDBtool_errorMSG)$COL_RESET
			exit 1
		fi
fi

cd ~/Downloads
rm -d -f -r ~/Downloads/ACE_wrappers
gzcat ~/Downloads/ACE-6.2.1.tar.gz | tar -xpf -
cd ~/Downloads/ACE_wrappers
export ACE_ROOT=$(pwd)
export PATH=$ACE_ROOT/bin:$PATH
export DYLD_LIBRARY_PATH=$ACE_ROOT/lib

	if [ $(sw_vers -productVersion | cut -c 1-4) = "10.8" ]
	then
		osx="mountainlion"
	fi
	if [ $(sw_vers -productVersion | cut -c 1-4) = "10.7" ]
	then
		osx="lion"
	fi
	if [ $(sw_vers -productVersion | cut -c 1-4) = "10.6" ]
	then
		osx="snowleopard"
	fi
	if [ $(sw_vers -productVersion | cut -c 1-4) = "10.5" ]
	then
		osx="leopard"
	fi

if f=$(xcode-select --print-path)
then
	echo -e 'Building ACE libs with one of the following parameters:'
		if test -d $f'//Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk'
		then
			echo -e ' - Use MacOSX10.6.sdk, Universal [1]'
		fi
		if test -d $f'//Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk'
		then
			echo -e ' - Use MacOSX10.7.sdk, Universal [2]'
		fi
		if test -d $f'//Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk'
		then
			echo -e ' - Use MacOSX10.8.sdk, Universal [3]'
		fi
		echo -e ' - Default ('$osx') [4]'
		read -p "To continue chose and press Enter. " prompt
else
	echo -e 'Install and initialize XCode first!'
	exit 1
fi

if [[ $prompt = "1" ]]
then

export MACOSX_DEPLOYMENT_TARGET=10.6
export DEPLOYMENT_TARGET=10.6
export OSX_SDK="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk"
export OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk"
export MACOSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk"
export CFLAGS="-mmacosx-version-min=10.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -arch i386 -arch x86_64"
export CCFLAGS="-arch i386 -arch x86_64"
export CXXFLAGS="-mmacosx-version-min=10.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -arch i386 -arch x86_64"
export LDFLAGS="-arch i386 -arch x86_64"
echo '#include "ace/config-macosx-snowleopard.h"' > ./ace/config.h
echo 'debug = 0' > ./include/makeinclude/platform_macros.GNU
echo 'shared_libs = 1' >> ./include/makeinclude/platform_macros.GNU
echo 'static_libs = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'install_rpath = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'include ${ACE_ROOT}/include/makeinclude/platform_macosx_snowleopard.GNU' >> ./include/makeinclude/platform_macros.GNU
echo 'INSTALL_PREFIX = /Applications/gcc44/ace' >> ./include/makeinclude/platform_macros.GNU

fi

if [[ $prompt = "2" ]]
then

export MACOSX_DEPLOYMENT_TARGET=10.7
export DEPLOYMENT_TARGET=10.7
export OSX_SDK="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"
export OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"
export MACOSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"
export CFLAGS="-mmacosx-version-min=10.7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -arch i386 -arch x86_64"
export CCFLAGS="-arch i386 -arch x86_64"
export CXXFLAGS="-mmacosx-version-min=10.7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -arch i386 -arch x86_64"
export LDFLAGS="-arch i386 -arch x86_64"
echo '#include "ace/config-macosx-lion.h"' > ./ace/config.h
echo 'debug = 0' > ./include/makeinclude/platform_macros.GNU
echo 'shared_libs = 1' >> ./include/makeinclude/platform_macros.GNU
echo 'static_libs = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'install_rpath = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'include ${ACE_ROOT}/include/makeinclude/platform_macosx_lion.GNU' >> ./include/makeinclude/platform_macros.GNU
echo 'INSTALL_PREFIX = /Applications/gcc44/ace' >> ./include/makeinclude/platform_macros.GNU

fi

if [[ $prompt = "3" ]]
then

export MACOSX_DEPLOYMENT_TARGET=10.8
export DEPLOYMENT_TARGET=10.8
export OSX_SDK="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk"
export OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk"
export MACOSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk"
export CFLAGS="-mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -arch i386 -arch x86_64"
export CCFLAGS="-arch i386 -arch x86_64"
export CXXFLAGS="-mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -arch i386 -arch x86_64"
export LDFLAGS="-arch i386 -arch x86_64"
echo '#include "ace/config-macosx-mountainlion.h"' > ./ace/config.h
echo 'debug = 0' > ./include/makeinclude/platform_macros.GNU
echo 'shared_libs = 1' >> ./include/makeinclude/platform_macros.GNU
echo 'static_libs = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'install_rpath = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'include ${ACE_ROOT}/include/makeinclude/platform_macosx_mountainlion.GNU' >> ./include/makeinclude/platform_macros.GNU
echo 'INSTALL_PREFIX = /Applications/gcc44/ace' >> ./include/makeinclude/platform_macros.GNU

fi

if [[ $prompt = "4" ]]
then
	
echo '#include "ace/config-macosx-'$osx'.h"' > ./ace/config.h
echo 'debug = 0' > ./include/makeinclude/platform_macros.GNU
echo 'shared_libs = 1' >> ./include/makeinclude/platform_macros.GNU
echo 'static_libs = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'install_rpath = 0' >> ./include/makeinclude/platform_macros.GNU
echo 'include ${ACE_ROOT}/include/makeinclude/platform_macosx_'$osx'.GNU' >> ./include/makeinclude/platform_macros.GNU
echo 'INSTALL_PREFIX = /Applications/gcc44/ace' >> ./include/makeinclude/platform_macros.GNU

fi

echo
echo -ne $COL_BLUE'[ACEtool] '$COL_RESET'Building ACE ...'
	if
		make -j $(sysctl -n hw.ncpu) > /dev/null 2>/tmp/TDBtool_errorMSG
	then
		echo -e $COL_GREEN' OK'$COL_RESET
		
		if
		! sudo -v
		then
			exit 1
		fi
		
		echo -ne $COL_BLUE'[ACEtool] '$COL_RESET'Installing ACE ...'
		if
			sudo ACE_ROOT=$ACE_ROOT make install > /dev/null 2>/tmp/TDBtool_errorMSG
		then
			echo -e $COL_GREEN' OK'$COL_RESET
		else
			echo -e $COL_RED' error'$COL_RESET
			echo -e $COL_RED'    error '$COL_WHITE$(/bin/cat /tmp/TDBtool_errorMSG)$COL_RESET
		fi
	else
		echo -e $COL_RED' error'$COL_RESET
		echo -e $COL_RED'    error '$COL_WHITE$(/bin/cat /tmp/TDBtool_errorMSG)$COL_RESET
	fi
cd /Applications/gcc44/ace
patch -f -p0 < <(curl http://jeremymeile.ch/files/emux7/ACE.patch)
install_name_tool -id /Applications/gcc44/ace/lib/libACE_Compression.dylib /Applications/gcc44/ace/lib/libACE_Compression.dylib
install_name_tool -id /Applications/gcc44/ace/lib/libACE_ETCL_Parser.dylib /Applications/gcc44/ace/lib/libACE_ETCL_Parser.dylib
install_name_tool -id /Applications/gcc44/ace/lib/libACE_ETCL.dylib /Applications/gcc44/ace/lib/libACE_ETCL.dylib
install_name_tool -id /Applications/gcc44/ace/lib/libACE_Monitor_Control.dylib /Applications/gcc44/ace/lib/libACE_Monitor_Control.dylib
install_name_tool -id /Applications/gcc44/ace/lib/libACE_RLECompression.dylib /Applications/gcc44/ace/lib/libACE_RLECompression.dylib
install_name_tool -id /Applications/gcc44/ace/lib/libACE_SSL.dylib /Applications/gcc44/ace/lib/libACE_SSL.dylib
install_name_tool -id /Applications/gcc44/ace/lib/libACE.dylib /Applications/gcc44/ace/lib/libACE.dylib
